default: &default
  tmdb:
    api_key: <%= ENV["TMDB_API_KEY"] %>
    api_v3: 'https://api.themoviedb.org/3/movie'
  movie_db_clear:
    time: 1800

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

staging:
  <<: *default
